name: rut_utils
description: Chilean RUT validation and formatting package. It includes methods to validate a RUT and a RutFormatter class to use on a Form.
version: 0.1.2
repository: https://github.com/smanriquez96/flutter_rut_utils


environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
